version: '3.8'

services:
  tomcat:
    build:
      context: .
      dockerfile: tomcat.Dockerfile
    environment:
      TZ: America/Guayaquil
      JPDA_ADDRESS: 8000
      JPDA_TRANSPORT: dt_socket
    image: tomcat
    container_name: tomcat
    restart: unless-stopped
    volumes:
      - webapps:/usr/local/tomcat/webapps
      - /opt/openbravo:/opt/openbravo
      - /srv:/srv
    working_dir: /opt/openbravo
    user: '1000'
    ports:
      - 7900:8000
      - 7901:8080
    networks:
      - default
    # depends_on:
    #   - postgres
    command: catalina.sh jpda run

volumes:
  webapps:

networks:
  default:
    external: true
    name: docker
