version: '3.8'

services:
  odoo:
    image: odoo:16
    container_name: odoo
    restart: unless-stopped
    depends_on:
      - postgres-15
    ports:
      - "8069:8069"
    environment:
      - TZ=America/Guayaquil
      - HOST=postgres-15
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo_data:/var/lib/odoo
      # - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - default

  postgres-15:
    image: postgres:15
    container_name: postgres-15
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      - TZ=America/Guayaquil
      - postgres_data:/var/lib/postgresql/data
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  odoo_data:
  postgres_data:


networks:
  default:
    external: true
    name: docker
