version: "3"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php
    container_name: php
    environment:
      TZ: America/Guayaquil
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - /opt/www:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - default

networks:
  default:
    external: true
    name: docker
